
[metadata]
name = automate-ui
version = 0.1.0
description = A framework to automate Web and Mobile UI
long_description = file: README.md
url = https://github.com/ironicalme/automate-web
author = Kartik Muchandi

[options]
python_requires = >=3.11, <=3.12
include_package_data = true
zip_safe = false
packages = find:

[options.extras_require]
dev =
    black
    isort
    flake8
    pep8-naming
    flake8-bugbear
    pylint
    mypy
    types-PyYAML

[isort]
#Google Python Style Guide
profile=google

# Preserve files with import order
skip=
    __init__.py,
    conftest.py,

[flake8]
ignore=
    # "Line too long", auto-formatters will determine length
    E501,
    # "Missing docstring in __init__", class should have docstring
    D107,
    # "Missing docstring in public module", not required
    D100,
    # "Missing docstring in public class", not required
    D101,
    # "Missing docstring in public method", not required
    D102,
    # "line break before binary operator", handled by autom formatter
    W503,
    # "whitespace before ':'",  handled by autom formatter
    E203,

per-file-ignores =
    # Ignore likely-intended usage of __init__.py
    */__init__.py:F401,D104,C0414,
    # Docstring requirement a bit much here, given other standards
    tests/*:D103

[mypy]
strict = true
namespace_packages = true
show_error_codes = true
implicit_reexport = true

[mypy-waiter]
# Newer mypy versions start flagging backwards-incompatible directives that don't matter
ignore_errors = true

[tool:pytest]
markers =
    smoke: for basic fast sanity tests
    e2e: journey style tests
