from .click import Click
from .mark import Mark
from .navigate import Navigate
from .press_key import PressKey
from .type_text import TypeText
from .wait import Wait
from .select import Select
from .send_request import SendRequest
from .clear_field import ClearField
from .refresh_page import RefreshPage
from .scroll import Scroll
from .screenshot_page import ScreenshotPage
from .upload import Upload
