from .click import Click
from .execute_deep_link import ExecuteDeepLink
from .mark import Mark
from .pick import Pick
from .scroll import Scroll
from .switch_context import SwitchContext
from .tap import Tap
from .type_text import TypeText
from .select import Select
